#生产环境prod
api.ipv.env=sandbox
api.ipv.sandbox_url=https://sandbox.ipipv.com
api.ipv.prod_url=https://api.ipipv.com

api.ipv.appKey=AK20260309151108
api.ipv.appSecret=Vi2znHmhauanxhbec9iedFdpsbf3a6xe

api.ipv.path.product_query=/api/open/app/product/query/v2
api.ipv.path.order_create=/api/open/app/order/create/v2
api.ipv.path.order_info=/api/open/app/order/info/v2