#生产环境prod，测试环境sandbox
#api.ipv.env=sandbox
api.ipv.env=prod
api.ipv.sandbox_url=https://sandbox.ipipv.com
api.ipv.prod_url=https://api.ipipv.com

api.ipv.sandbox.appKey=AK20260309151108
api.ipv.prod.appKey=AK20260317182703
api.ipv.sandbox.appSecret=Vi2znHmhauanxhbec9iedFdpsbf3a6xe
api.ipv.prod.appSecret=ch28Vkc4Gmrpdjrrczfw47wgxV96Fypi



#查询产品列表的接口地址
api.ipv.path.product_query=/api/open/app/product/query/v2
#创建订单的接口地址
api.ipv.path.order_create=/api/open/app/instance/open/v2
#查询订单信息的接口地址
api.ipv.path.order_info=/api/open/app/order/v2
#查询代理实例信息接口
api.ipv.path.instance_query=/api/open/app/instance/v2
#获取城市列表的接口地址
api.ipv.path.city_list=/api/open/app/city/list/v2
#获取地域列表的接口地址
api.ipv.path.area_list=/api/open/app/area/v2
#获取应用信息的接口地址
api.ipv.path.app_info=/api/open/app/info/v2