# \u5F53\u524D\u8FD0\u884C\u73AF\u5883\u8BBE\u7F6E: sandbox(\u6C99\u76D2) \u6216 prod(\u751F\u4EA7)
api.ipv.env=sandbox
# \u73AF\u5883\u57FA\u7840\u5730\u5740
api.ipv.sandbox_url=https://sandbox.ipipv.com
api.ipv.prod_url=https://api.ipipv.com

# \u901A\u7528\u914D\u7F6E
api.ipv.appKey=AK20260309151108
api.ipv.appSecret=Vi2znHmhauanxhbec9iedFdpsbf3a6xe

# \u63A5\u53E3\u8DEF\u5F84
api.ipv.path.product_query=/api/open/app/product/query/v2
api.ipv.path.order_create=/api/open/app/order/create/v2
api.ipv.path.order_info=/api/open/app/order/info/v2