jdbc.driver=com.mysql.cj.jdbc.Driver
jdbc.url=jdbc:mysql://112.124.51.99:3306/link_fast?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
jdbc.username=root
jdbc.password=LinkFast888!

jdbc.initialSize=5
jdbc.minIdle=5
jdbc.maxActive=20
jdbc.maxWait=60000